<?php

namespace moss\musicapp\exporter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-10 at 11:53:28.
 */
class playListerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var playLister
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $playlist = array(45,984, 34, 3753);
        $this->object = new playLister($playlist);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = NULL;
    }

    /**
     * Generated from @assert (0, 0) == 0.
     *
     * @covers moss\musicapp\exporter\playLister::getM3U8List
     */
    public function testGetM3U8List() {
        $this->assertNotEmpty(
                $this->object->getM3U8List()
        );
    }

    /**
     *
     * @covers moss\musicapp\exporter\playLister::getPlayList
     */
    public function testGetPlayList() {
        $this->assertNotEmpty(
                $this->object->getPlayList()
        );
    }
    
    /**
     *
     * @covers moss\musicapp\exporter\playLister::getPlayList
     */
    public function testconvertPlaylistToSongList() {
        $this->assertNotEmpty(
                $this->object->convertPlaylistToSongList()
        );
    }    
}
